MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: './weights/reid/resnext101_ibn_a_2.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'resnext101_ibn_a'
  NO_MARGIN: True

INPUT:
  SIZE_TEST: [384, 384]
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]

TEST:
  WEIGHT: './weights/reid/resnext101_ibn_a_2.pth'
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'
  FLIP_FEATS: 'no'
  EVAL: True

OUTPUT_DIR: './output/reid_results'
